### ISSUE TITLE
同步用什么api?

### ISSUE THREAD

**Issue by goodforever** [rxliuli/joplin-api#2]
同步用什么api?

**Comment by rxliuli** [comment]
目前没有 api 可以控制手动同步，也不需要

goodforever <notifications@github.com> 于 2020年6月27日周六 下午10:19写道：

**Comment by goodforever** [comment]
看了一下源码，原来你这个api是客户端啊，我还以为是server端的。

**Comment by rxliuli** [comment]
是的，joplin 的 server 并未分离为单独的仓库

goodforever <notifications@github.com> 于2020年6月28日周日 上午10:08写道：
